#!/bin/bash

bar() {
    $HOME/scripts/getProgressString 20 "●" "○" $1
}

set_brightness() {
    echo $1 | sudo tee /sys/class/backlight/intel_backlight/brightness
}

notify() {
    pct=`awk -v fin="$1" -v max="$2" 'BEGIN{ printf("%.0f", fin/max*100) }'`
    notify-send.sh --replace-file=/tmp/brightness-noti "Brightness: $pct%" "`bar $pct`"
}

max=`cat /sys/class/backlight/intel_backlight/max_brightness`
current=`cat /sys/class/backlight/intel_backlight/brightness`
step=`expr $max / 10`
min=1

case "$1" in
    "inc") 
        final=`expr $current + $step`
        if [ $final -gt $max ]
        then
            final=$max
        fi
        set_brightness $final
        notify $final $max
        ;;
    "dec")
        final=`expr $current - $step`
        if [ $final -lt $min ]
        then
            final=$min
        fi
        set_brightness $final
        notify $final $max
        ;;
    *)
        echo "Invalid parameter"
        exit 1
        ;;
esac

