#!/usr/bin/env bash

function switch_to_floating() {
	export KDEWM=$(which openbox)
	pkill i3
	openbox &
}

function switch_to_tiling() {
	export KDEWM=$(which i3)
	pkill openbox
	i3 &
}


case "$KDEWM" in
	# Current wm is tiling so switch to floating
	"/usr/bin/i3") switch_to_floating;;
	# Current wm is floating so switch to tiling
	"/usr/bin/openbox") switch_to_tiling;;
	*) echo "Unknown wm: $KDEWM";;
esac

